# Fake ZLIB finder for Emscripten builds (use Emscripten port via -sUSE_ZLIB=1)
set(ZLIB_FOUND TRUE)
set(ZLIB_INCLUDE_DIRS "")
set(ZLIB_LIBRARIES "")
set(ZLIB_LIBRARY "")
set(ZLIB_INCLUDE_DIR "/tmp/emsdk/upstream/emscripten/cache/sysroot/include")
set(ZLIB_VERSION_STRING "1.2.13")
if(NOT TARGET ZLIB::ZLIB)
  add_library(ZLIB::ZLIB INTERFACE IMPORTED)
endif()
