# Fake PNG finder for Emscripten builds (use Emscripten port via -sUSE_LIBPNG=1)
set(PNG_FOUND TRUE)
set(PNG_INCLUDE_DIRS "")
set(PNG_LIBRARIES "")
set(PNG_LIBRARY "")
set(PNG_PNG_INCLUDE_DIR "/tmp/emsdk/upstream/emscripten/cache/sysroot/include")
set(PNG_VERSION_STRING "1.6.37")
if(NOT TARGET PNG::PNG)
  add_library(PNG::PNG INTERFACE IMPORTED)
endif()
