# Fake Epoxy finder for Emscripten WASM builds (no OpenGL needed)
set(Epoxy_FOUND TRUE)
set(EPOXY_FOUND TRUE)
set(EPOXY_INCLUDE_DIRS "")
set(EPOXY_LIBRARIES "")
set(EPOXY_LIBRARY "")
if(NOT TARGET Epoxy::Epoxy)
  add_library(Epoxy::Epoxy INTERFACE IMPORTED)
endif()
