# Fake ZLIB finder for Emscripten builds (use Emscripten port via -sUSE_ZLIB=1)
if(DEFINED ENV{EMSDK})
  set(_ZLIB_SYSROOT "$ENV{EMSDK}/upstream/emscripten/cache/sysroot/include")
else()
  set(_ZLIB_SYSROOT "/emsdk/upstream/emscripten/cache/sysroot/include")
endif()

set(ZLIB_FOUND TRUE)
set(ZLIB_INCLUDE_DIRS "")
set(ZLIB_LIBRARIES "")
set(ZLIB_LIBRARY "")
set(ZLIB_INCLUDE_DIR "${_ZLIB_SYSROOT}")
set(ZLIB_VERSION_STRING "1.2.13")
if(NOT TARGET ZLIB::ZLIB)
  add_library(ZLIB::ZLIB INTERFACE IMPORTED)
endif()
