# Fake PNG finder for Emscripten builds (use Emscripten port via -sUSE_LIBPNG=1)
if(DEFINED ENV{EMSDK})
  set(_PNG_SYSROOT "$ENV{EMSDK}/upstream/emscripten/cache/sysroot/include")
else()
  set(_PNG_SYSROOT "/emsdk/upstream/emscripten/cache/sysroot/include")
endif()

set(PNG_FOUND TRUE)
set(PNG_INCLUDE_DIRS "")
set(PNG_LIBRARIES "")
set(PNG_LIBRARY "")
set(PNG_PNG_INCLUDE_DIR "${_PNG_SYSROOT}")
set(PNG_VERSION_STRING "1.6.37")
if(NOT TARGET PNG::PNG)
  add_library(PNG::PNG INTERFACE IMPORTED)
endif()
